#!/bin/bash
OPTIND=1         # Reset in case getopts has been used previously in the shell.
verbose=0

while getopts "v" opt
do
    case "$opt" in
        v)  verbose=1
            ;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift

test -e "$1" || exit
grep -H -r --only-matching --perl-regexp "http(s?):\/\/[^ \"\(\)\<\>\]]*" $1 | sort | uniq | sed 's/:/ /' |
while read -r file url
do
	set -- $(curl -m5 -w '%{http_code} %{url_effective}' -L -s -I --output /dev/null "$url")
	if test "$url" != "$2" # Is the original URL the same as the url_effective ?
	then # if not, append the new URL on the line
		echo -e "$1\t$file\t${url}\t$2"
	else
		test "$verbose" -gt 0 || { test "$1" -eq "200" && continue; }
		echo -e "$1\t$file\t$url"
	fi
done
